### ISSUE TITLE
안녕하세요, 전적이 개발자입니다.

### ISSUE THREAD

**Issue by kimcore** [dbgkswn7581/money_game#1]
본 레포에 포함된 코드 중 전적이 봇과 겹치는 부분이 다수 발견되어 삭제 또는 수정을 부탁드리고자 이슈를 남깁니다.
또한, 추후 모니터링을 위해 봇의 이름과 초대 링크도 남겨주시면 감사하겠습니다.

**Comment by dbgkswn7581** [comment]
빠른 시일 내에 삭제하도록 하겠습니다
불편 끼쳐드려 죄송합니다
1월이 지나기 전에 빠른 시일 내에 처리하겠습니다.

2021년 12월 31일 (금) 오후 11:12, kimcore ***@***.***>님이 작성:

**Comment by dbgkswn7581** [comment]
삭제를 먼저 한 후 천천히 수정을 하도록 하겠습니다
제가 봇을 수정을 마치면 모니터링 해주시어 추후 검토해주시면 정말 감사하겠습니다!

2021년 12월 31일 (금) 오후 11:26, wn han ***@***.***>님이 작성:

**Comment by kimcore** [comment]
빠른 답변 감사합니다!
